#!/usr/bin/env xonsh
# PATH configuration for xonsh - generated by darwin-config

# This file is dynamically generated by the PATH configuration
# and injected into the main xonsh configuration

import os

# PATH_ENTRIES_PLACEHOLDER will be replaced by the actual path entries
# by the Nix configuration generator