# Yazelix Fish Configuration
# This file is sourced by ~/.config/fish/config.fish

# Source generated initializers if they exist
# Using XDG-compliant state directory (not config directory)
set -l FISH_INITIALIZERS_DIR "$HOME/.local/share/yazelix/initializers/fish"

# Prefer the aggregate initializer if present (generated by Yazelix)
if test -f "$FISH_INITIALIZERS_DIR/yazelix_init.fish"
    source "$FISH_INITIALIZERS_DIR/yazelix_init.fish"
else
    # Source each initializer if it exists
    for file in $FISH_INITIALIZERS_DIR/*.fish
        if test -f $file
            source $file
        end
    end
end

# Yazelix aliases
alias yazelix="nu $HOME/.config/yazelix/nushell/scripts/core/launch_yazelix.nu"
alias lg='lazygit'

# Note: yzx command is defined in ~/.config/fish/config.fish (via v3 hooks) and is always available
