# Mise Tools Configuration
# This file tracks the runtime versions and global tools you want to install via mise
# Run 'manage-mise-tools install' to install all listed tools and runtimes

[runtimes]
# Java/JDK versions
java = [
  { version = "corretto-21.0.7.6.1", description = "Amazon Corretto JDK 21 (LTS)" },
  { version = "oracle-graalvm-24.0.1", description = "Oracle GraalVM 24 (latest)", global = true },
]

# Example of other runtimes you might manage:
# python = [
#   { version = "3.11.7", description = "Python 3.11 (stable)", global = true },
#   { version = "3.12.1", description = "Python 3.12 (latest)" },
# ]
# 
# nodejs = [
#   { version = "20.10.0", description = "Node.js 20 LTS", global = true },
#   { version = "21.5.0", description = "Node.js 21 (latest)" },
# ]
# 
# ruby = [
#   { version = "3.3.0", description = "Ruby 3.3 (latest)", global = true },
# ]
# 
# go = [
#   { version = "1.21.5", description = "Go 1.21 (latest)", global = true },
# ]

[global_tools]
# Tools installed globally via mise (if mise supports global tool installation)
# This section can be extended based on mise's global tool capabilities

[settings]
# Whether to auto-update runtimes on install
auto_update = true

# Whether to install exact versions (fallback to newer if unavailable)
use_fallback_newer = true

# Whether to sync global settings to mise global config
sync_global_config = true

# Whether to clean up old versions after installing new ones
cleanup_old_versions = false

# Timeout for installation (in seconds)
install_timeout = 600
